# Generated by Django 5.0.6 on 2024-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=None, max_length=20),
        ),
    ]
