# Generated by Django 5.0.6 on 2024-07-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_options_alter_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
