# Generated by Django 5.0.6 on 2024-07-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_rename_created_at_post_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
