# Generated by Django 5.0.6 on 2024-07-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_bio_alter_user_description_relations"),
    ]

    operations = []
