# Generated by Django 5.0.6 on 2024-07-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20240713_1932"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="followings_count",
        ),
    ]
